set_1 = {"rojo","blanco","azul"}
print (set_1)
set_1.add("violeta")
print (set_1)
set_1.add("dorado")
print (set_1)
set_1.discard("celeste")
print (set_1)
set_1.remove("dorado")
set_1.remove("blanco")
print (set_1)